### ISSUE TITLE
Do the plan work on Moodle 4.1

### ISSUE THREAD

**Issue by esugit** [YU-MITC/jmeter-quiz-testplan#3]
Hi test the plan on Moodle 4.1 but I think it respond with error:
Here is the result of the command
Creating summariser <summary>
Created the tree successfully using sample_testplan.jmx
Starting standalone test @ 2023 Apr 23 05:21:45 EET (1682220105171)
Waiting for possible Shutdown/StopTestNow/HeapDump/ThreadDump message on port 4445
summary +    347 in 00:00:15 =   23.9/s Avg:    61 Min:     0 Max:   946 Err:   347 (100.00%) Active: 24 Started: 24 Finished: 0
summary +    748 in 00:00:30 =   24.9/s Avg:    54 Min:     0 Max:   509 Err:   748 (100.00%) Active: 74 Started: 74 Finished: 0
summary =   1095 in 00:00:45 =   24.6/s Avg:    56 Min:     0 Max:   946 Err:  1095 (100.00%)
summary +    406 in 00:06:34 =    1.0/s Avg:    64 Min:     0 Max:   720 Err:   406 (100.00%) Active: 100 Started: 100 Finished: 0
summary =   1501 in 00:07:18 =    3.4/s Avg:    58 Min:     0 Max:   946 Err:  1501 (100.00%)
summary +     18 in 00:00:26 =    0.7/s Avg:   140 Min:     0 Max:   290 Err:    18 (100.00%) Active: 91 Started: 100 Finished: 9
summary =   1519 in 00:07:45 =    3.3/s Avg:    59 Min:     0 Max:   946 Err:  1519 (100.00%)
summary +     88 in 00:00:30 =    2.9/s Avg:   158 Min:     0 Max:   853 Err:    88 (100.00%) Active: 47 Started: 100 Finished: 53
summary =   1607 in 00:08:15 =    3.2/s Avg:    64 Min:     0 Max:   946 Err:  1607 (100.00%)
summary +     74 in 00:00:32 =    2.3/s Avg:   158 Min:     0 Max:   878 Err:    74 (100.00%) Active: 10 Started: 100 Finished: 90
summary =   1681 in 00:08:48 =    3.2/s Avg:    69 Min:     0 Max:   946 Err:  1681 (100.00%)
summary +     19 in 00:00:17 =    1.1/s Avg:   136 Min:     0 Max:   320 Err:    19 (100.00%) Active: 0 Started: 100 Finished: 100
summary =   1700 in 00:09:04 =    3.1/s Avg:    69 Min:     0 Max:   946 Err:  1700 (100.00%)
Tidying up ...    @ 2023 Apr 23 05:30:49 EET (1682220649752)
... end of run

**Comment by YU-MITC** [comment]
Hello @esugit

At first, we restored sample course file in our Moodle site (Moodle 4.1.1).
Second, we created test users, enrolled the users to sample course.
Next, we modified paramaeters (servername, cousreid, and cmid) in sample file, and we saved the file as "quiz_sample_configured.jmx", and put the test plan file and user list ("testuser.csv") in same directory.
Next, we executed this file at CLI mode as follows:

$ jmeter -n -t quiz_sample_configured.jmx -l moodle41_test_student100.jtl -Jclient=100 -Jloop=1

Creating summariser <summary>
Created the tree successfully using quiz_sample_configured.jmx
Starting the test @ Mon May 01 14:49:45 JST 2023 (1682920185193)
Waiting for possible Shutdown/StopTestNow/Heapdump message on port 4445
Warning: Nashorn engine is planned to be removed from a future JDK release
summary +    358 in 00:00:14 =   24.8/s Avg:    38 Min:     2 Max:   448 Err:     0 (0.00%) Active: 24 Started: 24 Finished: 0
summary +    739 in 00:00:30 =   24.7/s Avg:    31 Min:     1 Max:   274 Err:     0 (0.00%) Active: 74 Started: 74 Finished: 0
summary =   1097 in 00:00:44 =   24.7/s Avg:    34 Min:     1 Max:   448 Err:     0 (0.00%)
summary +    444 in 00:07:00 =    1.1/s Avg:    36 Min:     1 Max:   395 Err:     0 (0.00%) Active: 80 Started: 100 Finished: 20
summary =   1541 in 00:07:45 =    3.3/s Avg:    34 Min:     1 Max:   448 Err:     0 (0.00%)
summary +     84 in 00:00:30 =    2.8/s Avg:    75 Min:    33 Max:   130 Err:     0 (0.00%) Active: 38 Started: 100 Finished: 62
summary =   1625 in 00:08:14 =    3.3/s Avg:    36 Min:     1 Max:   448 Err:     0 (0.00%)
summary +     56 in 00:00:31 =    1.8/s Avg:    77 Min:    34 Max:   261 Err:     0 (0.00%) Active: 10 Started: 100 Finished: 90
summary =   1681 in 00:08:45 =    3.2/s Avg:    38 Min:     1 Max:   448 Err:     0 (0.00%)
summary +     19 in 00:00:20 =    0.9/s Avg:    73 Min:    36 Max:   134 Err:     0 (0.00%) Active: 0 Started: 100 Finished: 100
summary =   1700 in 00:09:06 =    3.1/s Avg:    38 Min:     1 Max:   448 Err:     0 (0.00%)
Tidying up ...    @ Mon May 01 14:58:51 JST 2023 (1682920731233)

No errors occurred.
And, minimum/average/maximum times between sending answers and receiving review page are were 238/308/644 msecs.
These results were verified by loading log file into "Aggregate Report" of the test plan file.
